lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - assets/nf-core-germline_logo_light.png
    - docs/images/nf-core-structural_logo_light.png
    - docs/images/nf-core-structural_logo_dark.png
  nextflow_config:
    - manifest.name
    - manifest.homePage
  files_unchanged:
    - LICENSE
  actions_ci: false
repository_type: pipeline
template:
  author: nvnieuwk
  description: A nextflow pipeline for calling structural variants
  name: structural
  prefix: nf-cmgg
