lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-structural_logo_light.png
    - docs/images/nf-core-structural_logo_light.png
    - docs/images/nf-core-structural_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-structural_logo_light.png
    - docs/images/nf-core-structural_logo_light.png
    - docs/images/nf-core-structural_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
repository_type: pipeline
template:
  author: nvnieuwk
  description: A nextflow pipeline for calling and annotating variants
  name: structural
  prefix: nf-cmgg
