lint:
  actions_ci: false
  files_exist:
    - CITATIONS.md
    - docs/README.md
    - CODE_OF_CONDUCT.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - assets/nf-core-structural_logo_light.png
    - docs/images/nf-core-structural_logo_light.png
    - docs/images/nf-core-structural_logo_dark.png
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - tests/default.nf.test
  files_unchanged:
    - LICENSE
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/linting.yml
    - assets/email_template.txt
    - assets/email_template.html
    - docs/README.md
    - .prettierignore
  included_configs: false
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: nvnieuwk
  description: A bioinformatics best-practice analysis pipeline for calling structural variants (SVs), copy number variants (CNVs) and repeat region expansions (RREs) from short DNA reads.
  force: false
  is_nfcore: false
  name: structural
  org: nf-cmgg
  outdir: .
  version: 0.4.0dev
