contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nf-cmgg-structural channel"
    url: https://nfcore.slack.com/channels/nf-cmgg-structural
    about: Discussion about the nf-core/nf-cmgg-structural pipeline
