FROM ubuntu:20.04
ENV TZ=Europe/Brussels
ENV PYTHONPATH=/svtest

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update
RUN apt install -y python3-pip libbz2-dev liblzma-dev

ADD ./svtest /svtest

RUN pip install ./svtest
